### ISSUE TITLE
Re-export `tock-registers`

### ISSUE THREAD

**Issue by tsoutsman** [rust-embedded/aarch64-cpu#19]
Hi,
I was wondering if you would consider re-exporting `tock_registers::interfaces::{Readable, Writeable}` because for 99% of use cases, the user ends up directly depending on `tock-register`. If there's a mismatch between the user's `tock-registers` version and `aarch64-cpu` version it can lead to some fairly cryptic errors.

Also, even if the user doesn't need to use `tock-registers` (i.e. they only use the `asm` module), it will still be in their dependency graph as `aarch64-cpu` unconditionally depends on `tock-registers`.

**Comment by nchong-at-aws** [comment]
Hi tsoutsman@, thanks for your suggestion. I'm not sure about the pros/cons here. Let me do some reading and suggest it to the WG.

**Comment by nchong-at-aws** [comment]
Apologies for the late reply. We're chatting about this at the next WG on Tue 29.

**Comment by nchong-at-aws** [comment]
Hi @tsoutsman , good news, no objections to re-exporting `tock_registers` as you suggest. Would you mind submitting a PR with the change?

We'll also do a minor version bump to signal the change.
