### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by bitboom** [rust-embedded/aarch64-cpu#21]
Hi, Thanks for your great work.

I was wondering if you would consider to release next version. I tried to use `TTBR0_EL2` but it didn't include in current version "9.3.1".

**Comment by nchong-at-aws** [comment]
Hi @bitboom,

Apologies for the slow reply. Yes, I think cutting a new release is a good idea. I'll update this ticket when it's done.

**Comment by nchong-at-aws** [comment]
Hope this helps! https://github.com/rust-embedded/aarch64-cpu/releases/tag/v9.4.0
