### ISSUE TITLE
Construct a register class from previously got `u64` value?

### ISSUE THREAD

**Issue by zhouhaoan** [rust-embedded/aarch64-cpu#25]
I got a `u64` register value from `get()` method. But when I want to parse the value to get specify fields, I can't use those API in the crate. Moreover, it seems that register modules and structs doesn't implement `From<u64>` trait. 
Are there some way to parse previously read values? Or just get values and read fields from raw registers?

**Comment by vbe0201** [comment]
You could use the [`read()` method on `Field` instances](https://docs.rs/tock-registers/0.8.1/tock_registers/fields/struct.Field.html#method.read) to extract bitfields out of raw integer values:

```rs
use aarch64_cpu::registers::*;

// Read the value of the register once
let esr = ESR_EL1.get();

// Extract fields from the `u64`
let ec = ESR_EL1::EC.read(esr);
let iss = ESR_EL1::ISS.read(esr);
```

**Comment by nchong-at-aws** [comment]
Closing as I think vbe0201's answer is what you need. Please reopen if that's not the case.
