### ISSUE TITLE
Crate not released after bumping tock_registers dependency to 0.9

### ISSUE THREAD

**Issue by berkus** [rust-embedded/aarch64-cpu#29]
And this is breaking my build - aarch64-cpu is the only crate that didn't update the dep.

Please make a(n automated) release (pipeline).

**Comment by berkus** [comment]
@andre-richter hi, congrats on joining Apple and maybe you could give me maintainer access on this crate? I'd set up automated releases and review the PRs, seems like you don't have much time for it right now ;)

**Comment by andre-richter** [comment]
Thanks @berkus.

Please reach out to @adamgreig for the process to get onboarded. I think you would be a great fit to help with this crate.

Also there was a handover to @nchong-at-aws in the past, you might want to align with them as well.

**Comment by berkus** [comment]
@adamgreig does not respond to email, any idea how to contact, @andre-richter ?

**Comment by adamgreig** [comment]
Sorry for the lack of response, I'm on holiday at the moment but I'll be back from Tuesday so can sort things out then.

**Comment by berkus** [comment]
@adamgreig got it, cheers!

**Comment by berkus** [comment]
@adamgreig hi, did you manage to take a look at my request?

**Comment by berkus** [comment]
-_-

**Comment by berkus** [comment]
Setting releases up in #30
